CREATE TABLE IF NOT EXISTS pets (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  name             TEXT    NOT NULL,
  type             TEXT    NOT NULL,
  breed            TEXT,
  age_years        REAL,
  birth_date       TEXT,
  sex              TEXT,
  weight_kg        REAL,
  color_markings   TEXT,
  microchip_id     TEXT,
  photo_url        TEXT,
  clinic_name      TEXT,
  vet_name         TEXT,
  clinic_phone     TEXT,
  clinic_address   TEXT,
  diet             TEXT,
  allergies        TEXT,
  medications      TEXT,
  vaccinations     TEXT,
  medical_history  TEXT,
  last_visit_date  TEXT,
  next_visit_date  TEXT,
  notes            TEXT,
  created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
  updated_at       TEXT    NOT NULL DEFAULT (datetime('now'))
);
